export const cmFormGerman = {
    firstName: 'Vorname',
    lastName: 'Nachname',
    fieldLabel: 'Branche',
    field: [
        'Metall', 'Elektro', 'KfZ+Fahrzeuge',
        'Wasser+Sanitär+Heizung+Klima+Rohr',
        'Holz', 'Bau+Ausbau', 'Lebensmittel',
        'Glas+Papier+Keramik', 'Foto+Medien',
        'Musikinstrumente', 'Bekleidung+Textil+Leder',
        'Gold+Silber+Uhr', 'Gesundheit+Körperpflege'
    ],
    profession: 'Handwerksberuf',
    qualification: 'Qualifikation/ Berufsabschluss',
    mainFocus: 'Tätikeitsschwerpunkte',
    experience: 'Berufserfahrung in Jahren',
    languages: 'Sprachkenntisse',
    skills: 'Niveau',
    veryGood: 'Sehr gut',
    good: 'Gut',
    base: 'Grundkenntnisse',
    english: 'Englisch',
    french: 'Französisch',
    other: 'Sonstige Sprachen',
    experienceAbroad: 'Auslandserfahrung',
    freeFromTo: 'Verfügbarkeit, mögliche Einsatzdauer',
    status: 'Status',
    ongoing: 'Aktuell',
    notOngoing: 'Nicht aktuell',
    submit: 'Abschicken'
};

export const cmFormEnglish = {
    firstName: 'Given name',
    lastName: 'Name',
    fieldLabel: 'Field',
    field: [
        'Metall', 'Elektro', 'KfZ+Fahrzeuge',
        'Wasser+Sanitär+Heizung+Klima+Rohr',
        'Holz', 'Bau+Ausbau', 'Lebensmittel',
        'Glas+Papier+Keramik', 'Foto+Medien',
        'Musikinstrumente', 'Bekleidung+Textil+Leder',
        'Gold+Silber+Uhr', 'Gesundheit+Körperpflege'
    ],
    profession: 'Profession',
    qualification: 'Qualification',
    mainFocus: 'Main focus',
    experience: 'Experience in years',
    languages: 'Languages',
    skills: 'Niveau',
    veryGood: 'Sehr gut',
    good: 'Gut',
    base: 'Grundkenntnisse',
    english: 'English',
    french: 'French',
    other: 'Other languages',
    experienceAbroad: 'Experience abroad',
    freeFromTo: 'Free from to',
    status: 'Status',
    ongoing: 'Ongoing',
    notOngoing: 'Ended',
    submit: 'Send'
};